CREATE TABLE IF NOT EXISTS messages (
id       VARCHAR(60)  PRIMARY KEY,
text     VARCHAR      NOT NULL
);

create table if not exists jokes (
 id      INT AUTO_INCREMENT PRIMARY KEY
,created TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
,updated TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
,family  VARCHAR(60) NOT NULL
,text    VARCHAR     NOT NULL
);