insert into jokes (family, text) values
 ('dadjokes', 'Did you hear about the claustrophobic astronaut? He just needed a little space.')
,('dadjokes', 'I told my friend 10 jokes to make him laugh. Sadly, no pun in ten did.')
,('dadjokes', 'I told my wife she was drawing her eyebrows too high. She looked surprised.')
,('dadjokes', 'I used to be a baker, but I couldn''t make enough dough.')
,('dadjokes', 'I used to play piano by ear, but now I use my hands.')
,('dadjokes', 'I''m reading a book on anti-gravity. It''s impossible to put down.')
,('dadjokes', 'Parallel lines have so much in common. It''s a shame they''ll never meet.')
,('dadjokes', 'Why did cowboys hang lanterns on their saddles at night? So they could use saddle-light navigation.')
,('dadjokes', 'Why did the bicycle fall over? Because it was two-tired.')
,('dadjokes', 'Why did the chicken join a band? Because it had the drumsticks.')
,('dadjokes', 'Why did the coffee file a police report? It got mugged.')
,('dadjokes', 'Why did the golfer bring two pairs of pants? In case he got a hole in one.')
,('dadjokes', 'Why did the math book look sad? Because it had so many problems.')
,('dadjokes', 'Why did the scarecrow win an award? Because he was outstanding in his field.')
,('dadjokes', 'Why did the tomato turn red? Because it saw the salad dressing.')
,('dadjokes', 'Why don''t scientists trust atoms? Because they make up everything.')
,('dadjokes', 'Why don''t scientists trust stairs? Because they''re always up to something.')
,('dadjokes', 'Why don''t skeletons fight each other? They don''t have the guts')
;
